// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVudgIQxUSUoiVzcb4TrI3OcnNgQ9-bIk',
    appId: '1:263078464216:web:6a6492e98fa8284df1a5ad',
    messagingSenderId: '263078464216',
    projectId: 'cinewavev1',
    authDomain: 'cinewavev1.firebaseapp.com',
    storageBucket: 'cinewavev1.appspot.com',
    measurementId: 'G-M0XZHS08S2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdordSZugRhaBCydEgH7qUFpa0SC2Jh1g',
    appId: '1:263078464216:android:b43de2f55159f37ff1a5ad',
    messagingSenderId: '263078464216',
    projectId: 'cinewavev1',
    storageBucket: 'cinewavev1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2PQPc5AtE24qt04ClzstdEPtz4_bGX9U',
    appId: '1:263078464216:ios:a379803064b39f56f1a5ad',
    messagingSenderId: '263078464216',
    projectId: 'cinewavev1',
    storageBucket: 'cinewavev1.appspot.com',
    iosBundleId: 'com.example.cinewave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2PQPc5AtE24qt04ClzstdEPtz4_bGX9U',
    appId: '1:263078464216:ios:05fe1bbde2c71bc3f1a5ad',
    messagingSenderId: '263078464216',
    projectId: 'cinewavev1',
    storageBucket: 'cinewavev1.appspot.com',
    iosBundleId: 'com.example.cinewave.RunnerTests',
  );
}
