// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqC0Nrb6D3Jy6RjEP0RlSdsOrvxmM71M',
    appId: '1:601897914244:web:25b33d20dd6050220dd7d1',
    messagingSenderId: '601897914244',
    projectId: 'cinewave-59b96',
    authDomain: 'cinewave-59b96.firebaseapp.com',
    databaseURL: 'https://cinewave-59b96-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinewave-59b96.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3ah-_vrTxEldxQymw7UrFMb3ONNfHNc',
    appId: '1:601897914244:android:fbcff13e57e8dba90dd7d1',
    messagingSenderId: '601897914244',
    projectId: 'cinewave-59b96',
    databaseURL: 'https://cinewave-59b96-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinewave-59b96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZZC5qBjOmdg54uwKmvdybD6hhMaf2elE',
    appId: '1:601897914244:ios:0ab5e2fd6d5181fa0dd7d1',
    messagingSenderId: '601897914244',
    projectId: 'cinewave-59b96',
    databaseURL: 'https://cinewave-59b96-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinewave-59b96.appspot.com',
    iosBundleId: 'com.example.cinewave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZZC5qBjOmdg54uwKmvdybD6hhMaf2elE',
    appId: '1:601897914244:ios:6a0a30951c4accf20dd7d1',
    messagingSenderId: '601897914244',
    projectId: 'cinewave-59b96',
    databaseURL: 'https://cinewave-59b96-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cinewave-59b96.appspot.com',
    iosBundleId: 'com.example.cinewave.RunnerTests',
  );
}
